services:
  caddy:
      image: caddy:latest
      container_name: caddy
      restart: always
      ports:
        - "80:80"
        - "443:443"
      environment:
        DOMAIN: ${DOMAIN}
      volumes:
        - ./.caddy_stuff/Caddyfile:/etc/caddy/Caddyfile
        - ./.caddy_stuff/caddy_data:/data
        - ./.caddy_stuff/caddy_config:/config
      depends_on:
        - frontend
        - backend
        
  db:
    image: postgres:15-alpine
    container_name: ${containername_db}
    restart: always
    environment:
      POSTGRES_USER: ${DB_user}
      POSTGRES_PASSWORD: ${DB_password}
      POSTGRES_DB: ${DB_name}
    volumes:
      - ./backend/.pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: ${containername_backend}
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app
      - .env:/app/.env
    depends_on:
          - db
    healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
          interval: 60s
          timeout: 2s
          retries: 5
          start_period: 5s
      
  frontend:
    build: ./frontend
    container_name: ${containername_frontend}
    volumes:
      - ./frontend:/app
      - /app/node_modules
